server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample?sslmode=disable
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
