server:
  port: 9090
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_db
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 3999
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false


